<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #ffcc00; background-color: #2a2a2a; padding: 30px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3); margin-bottom: 20px;">
    Data Mining
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #ff9900; background-color: #333333; padding: 20px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3); margin-bottom: 20px;">
    Lab 03
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #ff6600; background-color: #1c1c1c; padding: 20px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3); margin-bottom: 20px;">
    Syed Mansoor ul Hassan Bukhari
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #ffcc00; background-color: #222222; padding: 20px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3); margin-bottom: 20px;">
    BSAI - VII
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #ff3300; background-color: #1c1c1c; padding: 20px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);">
    2021-25
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #3399ff; background-color: #1c1c1c; padding: 20px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);">
    <span style="position: relative; top: -10px;">19</span> Nov, 2024
</div>


<div style="font-family: 'Arial', sans-serif; font-size: 20px; text-align: left; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">Question 01: </strong>
    <span style="color: #cccccc;">Create the following Data Matrix in Python.</span>
</div>
<img src="Pictures/Picture1.png" />

In [1]:
# First we need to import pandas for creating DataFrame
import pandas as pd
# We need to import numpy and pairwise_distances from sklearn for it
import numpy as np
from sklearn.metrics import pairwise_distances

In [2]:
# Create DataFrame
df = pd.DataFrame({"Object Identifier":[1, 2, 3, 4],
                   "test-1 (nominal)": ['Code A', 'Code B', 'Code C', 'Code A'],
                   'test-2 (ordinal)': ['excellent', 'fair', 'good', 'excellent'],
                   'test-3 (numeric)': [45, 22, 64, 28]})

# Set 'Object Identifier' as the index
df.set_index('Object Identifier', inplace=True)

# Convert 'test-2 (ordinal)' to a categorical type with ordered categories
df['test-2 (ordinal)'] = pd.Categorical(df['test-2 (ordinal)'], categories=['fair', 'good', 'excellent'], ordered=True)

In [3]:
df

test-1 (nominal) test-2 (ordinal)  test-3 (numeric)
Object Identifier                                                    
1                           Code A        excellent                45
2                           Code B             fair                22
3                           Code C             good                64
4                           Code A        excellent                28

In [4]:
df.dtypes

test-1 (nominal)      object
test-2 (ordinal)    category
test-3 (numeric)       int64
dtype: object

<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">Summary:</strong><br><br>
    <span style="color: #cccccc;">- <span style="color: #ffcc00;">Nominal</span> columns are typically categorical with no inherent order (e.g., <code>test-1</code>).</span><br>
    <span style="color: #cccccc;">- <span style="color: #00bcd4;">Ordinal</span> columns are categorical but have a specific order (e.g., <code>test-2</code>).</span><br>
    <span style="color: #cccccc;">- <span style="color: #4caf50;">Numeric</span> columns contain numerical values (e.g., <code>test-3</code>).</span>
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 20px; text-align: left; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">Q2: </strong>
    <span style="color: #cccccc;">Generate the dissimilarities matrices using appropriate proximity measures for:</span><br>
    <ol style="color: #cccccc;">
        <li>Nominal Attributes</li>
        <li>Ordinal Attributes</li>
        <li>Numerical Attributes</li>
    </ol>
    <span style="color: #cccccc;">Use the data matrix created in the previous lab where required. You can assume the missing attributes (such as numeric).</span>
</div>


<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
<center>
  <span style="color:#4682B4; font-size:22px; font-weight: bold; padding: 5px;">Dissimilarity for Nominal Attributes (test-1)</span>
</center>
</div>

In [5]:
# Use simple matching (Hamming distance)
def nominal_dissimilarity(df_nominal):
    # Create a binary dissimilarity matrix
    return pairwise_distances(df_nominal, metric='hamming')

# Convert 'test-1 (nominal)' to categorical for pairwise comparison
nominal_df = pd.get_dummies(df['test-1 (nominal)'])

In [6]:
nominal_df

Code A  Code B  Code C
Object Identifier                        
1                    True   False   False
2                   False    True   False
3                   False   False    True
4                    True   False   False

In [7]:
# Calculate dissimilarity matrix for nominal attributes
nominal_dissimilarity_matrix = nominal_dissimilarity(nominal_df)
print("Nominal Dissimilarity Matrix:")
nominal_dissimilarity_matrix

Nominal Dissimilarity Matrix:


array([[0.        , 0.66666667, 0.66666667, 0.        ],
       [0.66666667, 0.        , 0.66666667, 0.66666667],
       [0.66666667, 0.66666667, 0.        , 0.66666667],
       [0.        , 0.66666667, 0.66666667, 0.        ]])

<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
<center>
  <span style="color:#4682B4; font-size:22px; font-weight: bold; padding: 5px;">Dissimilarity for Ordinal Attributes (test-2)</span>
</center>
</div>

In [7]:
# Use the absolute difference between the ranks
def ordinal_dissimilarity(df_ordinal):
    # Convert ordinal categories to their rank positions
    return pairwise_distances(df_ordinal, metric='cityblock')

# Calculate dissimilarity matrix for ordinal attributes
ordinal_dissimilarity_matrix = ordinal_dissimilarity(df['test-2 (ordinal)'].cat.codes.values.reshape(-1, 1))

In [8]:
print("\nOrdinal Dissimilarity Matrix:")
print(ordinal_dissimilarity_matrix)


Ordinal Dissimilarity Matrix:
[[0. 1. 1. 0.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [0. 1. 1. 0.]]


<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
<center>
  <span style="color:#4682B4; font-size:22px; font-weight: bold; padding: 5px;">Dissimilarity for Numerical Attributes (test-3)</span>
</center>
</div>

In [9]:
# Use Euclidean distance for numeric columns
def numerical_dissimilarity(df_numerical):
    # Calculate Euclidean distance
    return pairwise_distances(df_numerical, metric='euclidean')

# Calculate dissimilarity matrix for numerical attributes
numerical_dissimilarity_matrix = numerical_dissimilarity(df[['test-3 (numeric)']])

In [10]:
print("\nNumerical Dissimilarity Matrix:")
print(numerical_dissimilarity_matrix)


Numerical Dissimilarity Matrix:
[[ 0. 23. 19. 17.]
 [23.  0. 42.  6.]
 [19. 42.  0. 36.]
 [17.  6. 36.  0.]]


<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">Dissimilarity Calculations for Nominal, Ordinal, and Numerical Attributes</strong><br><br>
    <span style="color: #cccccc;">In this section, we calculate the dissimilarity matrices for three types of data attributes: <span style="color: #ffcc00;">Nominal</span>, <span style="color: #00bcd4;">Ordinal</span>, and <span style="color: #4caf50;">Numerical</span>. Each type of attribute is compared using different distance metrics suited to their characteristics: <span style="color: #ffcc00;">Hamming Distance</span> for nominal attributes, <span style="color: #00bcd4;">Manhattan Distance</span> for ordinal attributes, and <span style="color: #4caf50;">Euclidean Distance</span> for numerical attributes.</span.<br><br>
    <strong style="color: #ffcc00;">1. Dissimilarity for Nominal Attributes (Hamming Distance)</strong><br>
    <span style="color: #cccccc;">Nominal data refers to categorical data where the values represent categories without any inherent order (e.g., colors: "Red", "Blue", "Green").</span><br>
    <span style="color: #cccccc;">- <span style="color: #ffcc00;">Hamming Distance</span> is used to measure dissimilarity in nominal data. It works by comparing the corresponding values of two elements in the dataset and counting how many positions have different values. It is appropriate for binary or categorical variables.</span><br>
    <span style="color: #cccccc;">- The nominal data is converted into binary (dummy/indicator) variables, and the dissimilarity matrix is calculated using <span style="color: #ffcc00;">Hamming distance</span>, which counts the number of different categorical values between each pair of observations.</span><br><br>
    <strong style="color: #ffcc00;">2. Dissimilarity for Ordinal Attributes (Manhattan / Cityblock Distance)</strong><br>
    <span style="color: #cccccc;">Ordinal data refers to categorical variables with a defined order or ranking but without a consistent difference between categories (e.g., "Low", "Medium", "High").</span><br>
    <span style="color: #cccccc;">- <span style="color: #00bcd4;">Manhattan Distance (also known as Cityblock distance)</span> is used for ordinal attributes. This metric calculates the sum of absolute differences between the ranks of the categories, making it useful for attributes where the categories have a meaningful order.</span><br>
    <span style="color: #cccccc;">- To compute dissimilarity for ordinal data, the categorical values are first converted into numerical ranks. Then, the dissimilarity is calculated based on the absolute differences between the ranks using <span style="color: #00bcd4;">Manhattan distance</span>.</span><br><br>
    <strong style="color: #ffcc00;">3. Dissimilarity for Numerical Attributes (Euclidean Distance)</strong><br>
    <span style="color: #cccccc;">Numerical data consists of continuous or discrete variables that represent quantities, such as "Age", "Height", or "Weight".</span><br>
    <span style="color: #cccccc;">- <span style="color: #4caf50;">Euclidean Distance</span> is the most common metric for calculating dissimilarity between numerical data points. It computes the straight-line distance between two points in a multi-dimensional space, which is ideal for continuous variables.</span><br>
    <span style="color: #cccccc;">- The dissimilarity matrix is computed by calculating the Euclidean distance between each pair of numerical values in the dataset, taking into account the actual numeric differences.</span><br><br>