<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #ffcc00; background-color: #2a2a2a; padding: 30px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3); margin-bottom: 20px;">
    Data Mining
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #ff9900; background-color: #333333; padding: 20px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3); margin-bottom: 20px;">
    Lab 01
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #ff6600; background-color: #1c1c1c; padding: 20px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3); margin-bottom: 20px;">
    Syed Mansoor ul Hassan Bukhari
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #ffcc00; background-color: #222222; padding: 20px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3); margin-bottom: 20px;">
    BSAI - VII
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #ff3300; background-color: #1c1c1c; padding: 20px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);">
    2021-25
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #3399ff; background-color: #1c1c1c; padding: 20px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);">
    <span style="position: relative; top: -10px;">05</span> Nov, 2024
</div>


<div style="font-family: 'Arial', sans-serif; font-size: 20px; text-align: left; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">Question 01: </strong>
    <span style="color: #cccccc;">Write a Python program to create an array of 5 integers and display the array items.</span>
</div>


In [1]:
import numpy as np

In [2]:
a = np.array([4,5,6,7,8])

In [3]:
a[1]

5

<div style="font-family: 'Arial', sans-serif; font-size: 20px; text-align: left; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">Question 02: </strong>
    <span style="color: #cccccc;">Write a Python program to convert an array to an ordinary list with the same elements.</span>
</dv>
 


In [4]:
a = np.array([5,6,7,8,9])

In [5]:
type(a)

numpy.ndarray

In [6]:
a = list(a)

In [7]:
type(a)

list

<div style="font-family: 'Arial', sans-serif; font-size: 20px; text-align: left; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">Question 03: </strong>
    <span style="color: #cccccc;">Write a Python program to find out if a given array of integers contains any duplicate elements. Return true if any value appears twice in the array, and return false if every element is distinct.</span>
</div>


In [8]:
def contains_duplicate(nums):
    # Create an empty set to track unique elements
    seen = set()
    
    # Loop through each element in the array
    for num in nums:
        # If the element is already in the set, we found a duplicate
        if num in seen:
            return True
        # Otherwise, add the element to the set
        seen.add(num)
    
    # If no duplicates are found, return False
    return False

In [9]:
arr = [1, 2, 3, 4, 5]
print(contains_duplicate(arr))

False


In [10]:
arr2 = [1, 2, 3, 4, 5, 3]
print(contains_duplicate(arr2)) 

True


<div style="font-family: 'Arial', sans-serif; font-size: 20px; text-align: left; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">Question 04: </strong>
    <span style="color: #cccccc;">Write a Python program that removes all duplicate elements from an array and returns a new array.</span>
</dv>


In [11]:
def remove_duplicate(nums):
    seen = set()
    for num in nums:
        if num in seen:
            pass
        seen.add(num)
    return list(seen)

In [12]:
a = [1,2,3,3,4,5]
remove_duplicate(a)

[1, 2, 3, 4, 5]

In [13]:
a = [4,5,6,7]
remove_duplicate(a)

[4, 5, 6, 7]

<div style="font-family: 'Arial', sans-serif; font-size: 20px; text-align: left; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">Question 05: </strong>
    <span style="color: #cccccc;">Write a Python program to demonstrate matrix operations.</span>
</dv>


In [14]:
matrix_A = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix_B = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]

In [15]:
# Matrix Addition
def matrix_addition(A, B):
    if len(A) != len(B) or len(A[0]) != len(B[0]):
        raise ValueError("Matrices must have the same dimensions for addition")
    result = []
    for i in range(len(A)):
        row = []
        for j in range(len(A[0])):
            row.append(A[i][j] + B[i][j])
        result.append(row)
    return result

# Matrix Subtraction
def matrix_subtraction(A, B):
    if len(A) != len(B) or len(A[0]) != len(B[0]):
        raise ValueError("Matrices must have the same dimensions for subtraction")
    result = []
    for i in range(len(A)):
        row = []
        for j in range(len(A[0])):
            row.append(A[i][j] - B[i][j])
        result.append(row)
    return result

# Matrix Multiplication
def matrix_multiplication(A, B):
    if len(A[0]) != len(B):  # Number of columns in A must be equal to number of rows in B
        raise ValueError("Number of columns in A must be equal to number of rows in B for multiplication")
    result = []
    for i in range(len(A)):  # Iterate over rows of A
        row = []
        for j in range(len(B[0])):  # Iterate over columns of B
            value = 0
            for k in range(len(B)):  # Sum over the columns of A and rows of B
                value += A[i][k] * B[k][j]
            row.append(value)
        result.append(row)
    return result

# Matrix Transposition
def matrix_transpose(A):
    result = []
    for j in range(len(A[0])):
        row = []
        for i in range(len(A)):
            row.append(A[i][j])
        result.append(row)
    return result

<div style="font-family: 'Arial', sans-serif; font-size: 20px; text-align: center; color: #00bcd4; background-color: #1c1c1c; padding: 25px; border: 3px solid #333333; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <span style="color: #00bcd4;"><strong>Showcasing The Functionality</strong></span>
</div>

In [16]:
# Addition
print("Matrix A:")
for row in matrix_A:
    print(row)

print("Matrix B:")
for row in matrix_B:
    print(row)

print("\nMatrix A + Matrix B:")
result_add = matrix_addition(matrix_A, matrix_B)
for row in result_add:
    print(row)

Matrix A:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Matrix B:
[9, 8, 7]
[6, 5, 4]
[3, 2, 1]

Matrix A + Matrix B:
[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [17]:
# Subtraction
print("\nMatrix A - Matrix B:")
result_sub = matrix_subtraction(matrix_A, matrix_B)
for row in result_sub:
    print(row)


Matrix A - Matrix B:
[-8, -6, -4]
[-2, 0, 2]
[4, 6, 8]


In [18]:
# Multiplication
print("\nMatrix A * Matrix B:")
result_mul = matrix_multiplication(matrix_A, matrix_B)
for row in result_mul:
    print(row)



Matrix A * Matrix B:
[30, 24, 18]
[84, 69, 54]
[138, 114, 90]


In [19]:
# Transposition of Matrix A
print("\nTranspose of Matrix A:")
result_transpose = matrix_transpose(matrix_A)
for row in result_transpose:
    print(row)



Transpose of Matrix A:
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


<div style="font-family: 'Arial', sans-serif; font-size: 20px; text-align: center; color: #00bcd4; background-color: #1c1c1c; padding: 25px; border: 3px solid #333333; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <span style="color: #00bcd4;"><strong>Alternatively, We Can Use NumPy For Matrix Operations To Simplify</strong></span>
</div>

In [20]:
print("\nUsing NumPy for matrix addition:")
np_A = np.array(matrix_A)
np_B = np.array(matrix_B)

result_np_add = np_A + np_B
print(result_np_add)

print("\nUsing NumPy for matrix multiplication:")
result_np_mul = np.dot(np_A, np_B)
print(result_np_mul)



Using NumPy for matrix addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Using NumPy for matrix multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


<div style="font-family: 'Arial', sans-serif; font-size: 20px; text-align: left; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">Question 06: </strong>
    <span style="color: #cccccc;">Write a Python program to create a pandas DataFrame.</span>
</dv>


In [21]:
import pandas as pd

In [22]:
# Data as a dictionary
data = {
    'Name': ['Ahmed', 'Fatimah', 'Ali', 'Amina', 'Omar', 'Zainab', 'Ibrahim'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male']
}

In [23]:
# Create DataFrame
df = pd.DataFrame(data)

In [24]:
df.head()

Name  Gender
0    Ahmed    Male
1  Fatimah  Female
2      Ali    Male
3    Amina  Female
4     Omar    Male

<div style="font-family: 'Arial', sans-serif; font-size: 20px; text-align: left; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">Question 07: </strong>
    <span style="color: #cccccc;">Write a Python code to add data in a DataFrame.</span>
</dv>


In [25]:
# Data as a dictionary
data = {
    'Name': ['Ahmed', 'Fatimah', 'Ali', 'Amina', 'Omar', 'Zainab', 'Ibrahim'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male']
}

In [26]:
df = pd.DataFrame(data)
new_r = pd.DataFrame({
    'Name':['Mansoor'],
    'Gender': ['Male']
})

In [27]:
df = pd.concat([df, new_r], ignore_index=True)

In [28]:
df.tail()

Name  Gender
3    Amina  Female
4     Omar    Male
5   Zainab  Female
6  Ibrahim    Male
7  Mansoor    Male

<div style="font-family: 'Arial', sans-serif; font-size: 20px; text-align: left; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">Question 08: </strong>
    <span style="color: #cccccc;">Write a Python program to drop a column from a DataFrame.</span>
</dv>


In [29]:
df.drop(columns=['Gender'], inplace=True, axis=1)

In [30]:
df.head(1)

Name
0  Ahmed

<div style="font-family: 'Arial', sans-serif; font-size: 20px; text-align: left; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">Question 09: </strong>
    <span style="color: #cccccc;">Write a Python program to drop a row from a DataFrame.</span>
</dv>


In [31]:
df.shape

(8, 1)

In [32]:
df.drop(2, inplace=True)

In [33]:
df.shape

(7, 1)